---
title: "Data Science Salary Predictor"
author: UBC MDS Cohort 7 DSCI 522 Team 16 - Chen Lin, Jonah Hamilton, Mike Guron, Tanmay Agarwal
date: "11/26/2022" 
output: 
  html_document:
    toc: TRUE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(kableExtra)
```

# Data Preprocessing

## Dataset

The dataset used for this prediction model building of Data Science Salary Predictor is from 2022 Stack Overflow Annual Developer Survey, can be obtained from links below:

[Dataset download page](https://insights.stackoverflow.com/survey)

[Download dataset directly to your local](https://info.stackoverflowsolutions.com/rs/719-EMH-566/images/stack-overflow-developer-survey-2022.zip)

The overall survey features over 70,000 responses fielded from over 180 countries, examining all aspects of the developer experience from learning to code to favorite technologies for version control and workplace experience.

A detailed summary of the overall dataset can be found [here](https://survey.stackoverflow.co/2022/)

Each row in the data set represents the survey response of an individual working in a data-related career including information on skills, experience, technologies worked with, and demographics.

Since we are interested in developing a predictor for North American Data Science Salaries, the dataset was subset to only include responses from individuals in Canada and the United States as a proxy for the whole of North America as the bulk of the responses are from these two countries.

Also by limiting the salary range with \$500k, making the predictor more reliable for the majority of the Data Science community.

## Feature Descriptions

The full feature description schema can be found [here]('../data/raw/survey_results_schema.csv').

Below are the descriptions based on the types of features, which are used for data pre-processing:

### Numeric Features

`YearsCode`: Including any education, how many years have you been coding in total? Range from 0 year to over 50 years

`YearsCodePro`: NOT including education, how many years have you coded professionally (as a part of your work)? Range from 0 year to over 50 years

`WorkExp`: How many years of working experience do you have? Range from 0 year to over 50 years

### Categorical Features

`OrgSize`: Approximately how many people are employed by the company or organization you currently work for?

9 unique values ['20 to 99 employees', '1,000 to 4,999 employees', '500 to 999 employees', '10,000 or more employees', '5,000 to 9,999 employees', 'Just me - I am a freelancer, sole proprietor, etc.', '2 to 9 employees', '100 to 499 employees', '10 to 19 employees', 'I don't know'],

`RemoteWork`: Which best describes your current work situation?

3 unique values ['Fully remote', 'Hybrid (some remote, some in-person)', 'Full in-person']

#### Binary Features

`MainBranch`: Which of the following options best describes you today? Here, by "developer" we mean "someone who writes code."

1 = 'I am not primarily a developer, but I write code sometimes as part of my work', 0 = 'I am a developer by profession'

`Country`:Where do you live?

1 = 'United States of America', 0 = 'Canada'

### Oridinal Features

`EdLevel`: Which of the following best describes the highest level of formal education that you've completed? \*

Following the order below with assigned value form 0 to 8

['Something else', 'Primary/elementary school', 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)','Some college/university study without earning a degree', 'Associate degree (A.A., A.S., etc.)', "Bachelor's degree (B.A., B.S., B.Eng., etc.)", "Master's degree (M.A., M.S., M.Eng., MBA, etc.)",'Professional degree (JD, MD, etc.)', 'Other doctoral degree (Ph.D., Ed.D., etc.)']

`Age`: What is your age?

Following the order below with assigned value form 0 to 7

['Prefer not to say', 'Under 18 years old', '18-24 years old','25-34 years old','35-44 years old','45-54 years old', '55-64 years old','65 years or older']

### Multi-selection question features

`DevType`: Which of the following describes your current job? Please select all that apply.

`LanguageHaveWorkedWith`: Which programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year?

`DatabaseHaveWorkedWith`: Which database environments have you done extensive development work in over the past year, and which do you want to work in over the next year?

`PlatformHaveWorkedWith`: Which cloud platforms have you done extensive development work in over the past year, and which do you want to work in over the next year?

`WebframeHaveWorkedWith`: Which web frameworks and web technologies have you done extensive development work in over the past year, and which do you want to work in over the next year?

`MiscTechHaveWorkedWith`: Which other frameworks and libraries have you done extensive development work in over the past year, and which do you want to work in over the next year?

`ToolsTechHaveWorkedWith`: Which developer tools have you done extensive development work in over the past year, and which do you want to work in over the next year?

`NEWCollabToolsHaveWorkedWith`: Which development environmentsdid you use regularly over the past year, and which do you want to work with over the next year?

`OpSysProfessional use`: What is the primary operating system in which you work?

`VCInteraction`: How do you interact with your version control system? Select all that apply.

`VersionControlSystem`: What are the primary version control systems you use?

`OfficeStackAsyncHaveWorkedWith`: Which collaborative work management toolsdid you use regularly over the past year, and which do you want to w ork with over the next year?

`Employment`: Which of the following best describes your current employment status?

## Preprocessing Data

The Data was first filter by country, job type and converted compensation.

Then it is imputed to fill the missing values.

The train split will be 90% of the overall filtered data and test splits will be 10% of the overall filtered data.

The by defining the column transformer for different types of features, the train split was encoded for EDA use, which will be explained in the next section.

# Model Selection
The final model would be able to predict the Data Science yearly converted salary when giving new data point representing a North American (Canada or US) Data Science related job.

The following models were used for evaluation through cross validation by using the train split data, along with the designated proprocessor:

- DummyRegressor
- KNeighborsRegressor
- Ridge
- RandomForestRegressor
- Lasso

The result decision was based on the mean R2 score from the cross validation. The result can be see below:

<!Tanmay add his cv result table>

And the RandomForestRegressor gives the highest R2 validation score of 0.35, thus RandomForestRegressor will be used for the upcoming hyperparameter tuning and final model building.

## Hyper-parameter tuning
By using the RandomizedSearchCV, the best model is selection based on best score and best parameters as below:

<!Tanmay add his best-related information>

## Final model building
By using the best model with the best hyperparameter as mentioned above, the final model score <!Tanmay add final score> against the test data.

# Further Improvements

1 Feature engineering and importance analysis can help to reduce the impact from any noise feature. Removing those noise features can be done based on the correlation with the target feature, which is the converted yearly compensation.

2.  For those feature containing null values or values as 'unspecified', if there is a better way to make those values can be more meaningful, it would be helpful to improve the overall model performance.

3.  For regression problems, it is necessary to have more data points. The solution could be to include more survey entries from recent years, not only 2022. This could make the prediction accuracy higher.

Final report was build by using the following software or libraries: \
R [@R], \
Rmarkdown [@Rrmarkdown], \
Knitr [@knitr], \
kableExtra [@kableextra], \
tidyverse [@tidy]  \
Python [@python] \
pandas[@pandas], \
numpy[@numpy], \
scikit-learn[@scikit-learn], \
altair[@altair], \

# References
